# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ïŒŠ  î‚  î­„  ï‰™  ïžŸ  ï¯ˆ  ó°„Š  ó°»€  ó±Ÿ°  ó°ƒ«  ó°  ó° ¬  ó±¢  ó°Œ¢
format = """
[â–‘â–’â–“](#a3aed2)\
[ ó°»€ ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#4e7aad fg:#a3aed2)\
$sudo\
$username\
$hostname\
$localip\
[î‚´](bg:#769ff0 fg:#4e7aad)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$docker_context\
$golang\
$python\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
$battery\
\n$character"""

# Inserts a blank line between shell prompts
add_newline = false

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = " ðŸ§™ "
style = "bg:#4e7aad"

[username]
disabled = false
show_always = false
style_user = "fg:#e3e5e5 bg:#4e7aad"
style_root = "fg:#ff0000 bold bg:#4e7aad"
format = '[$user]($style)'

[hostname]
disabled = false
ssh_only = true
style = "fg:#e3e5e5 bg:#4e7aad"
format = "[@$hostname]($style)"

[localip]
disabled = false
ssh_only = true
style = "fg:#e3e5e5 bg:#4e7aad"
format = "[ $localipv4 ]($style)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[docker_context]
symbol = "ïŒˆ  "
style = "bg:#212736"
format = "[ $symbol $context ]($style) $path"

[golang]
symbol = "ï³‘ "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = "îˆµ "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[X](bold red)'
vimcmd_symbol = '[<](bold blue)'
